name: Deployment

on:
  repository_dispatch:
    types: [test_and_build]

jobs:
  test_and_build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: e2e tests
        uses: cypress-io/github-action@v2
        timeout-minutes: 5
        with:
          browser: chrome
          run: npm run cypress
          start: npm run start
          wait-on: "http://localhost:3001", "http://localhost:3000", "http://localhost:3003"
          wait-on-timeout: 180

      - name: deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: coalesceforum
          heroku_email: parkpatrick1@gmail.com
          healthcheck: http://coalesceforum.herokuapp.com/ping
          checkstring: pong
          procfile: "web: node index.ts"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}